### ISSUE TITLE
Issues with loopable import blocks and CLI on windows platform

### ISSUE THREAD

**Issue by ShadowScorpion** [opentofu/opentofu#1528]
### Did you test the provider-defined functions?

Tested, worked

### Additional feedback / details on the provider-defined functions

Tested with multiple corefunc options. Works well.

### Did you test the `for_each` on the import block?

Tested, did not work / had problems

### Additional feedback / details on the import block

Tested on multiple variants, but facing problems, each time when trying to import.

Platform: 
```
./tofu -v
OpenTofu v1.7.0-beta1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/aws v5.46.0
```

Steps to reproduce:
- Create on AWS the SSM parameter resources (working code):

```
variable "ssm_parameters_names_list" {
  type    = list(string)
  default = ["/import/test1", "/import/test2"]
}

variable "ssm_parameters_values_list" {
  type    = list(string)
  default = ["test1text", "test2text"]
}

variable "ssm_parameters_ids" {
  type    = list(string)
  default = ["arn:aws:ssm:eu-west-1:123456789012:parameter/import/test1", "arn:aws:ssm:eu-west-1:123456789012:parameter/import/test2"]
}

resource "aws_ssm_parameter" "test" {
  count = length(var.ssm_parameters_names_list)

  name  = var.ssm_parameters_names_list[count.index]
  type  = "String"
  value = var.ssm_parameters_values_list[count.index]
}

output "ssm_ids" {
  value = aws_ssm_parameter.test[*].id
}
```

```
`tofu init ; tofu apply
...
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

ssm_ids = [
  "/import/test1",
  "/import/test2",
]
```

- Remove the state file and any cache
```
rm -f ./terraform.tfstate ; rm -rf ./.*`

- Add import block:
`import {
  for_each = { for idx, name in var.ssm_parameters_names_list : idx => name }
  to = aws_ssm_parameter.test[each.key]
  id = each.value
}
```

And after using this block I'm getting the problem:

> │ Error: Configuration for import target does not exist
> │
> │ The configuration for the given import aws_ssm_parameter.test["0"] does not exist. All target instances must have an associated configuration to be imported.
> ╵
> ╷
> │ Error: Configuration for import target does not exist
> │
> │ The configuration for the given import aws_ssm_parameter.test["1"] does not exist. All target instances must have an associated configuration to be imported.

Like for the Windows version, I have completely different error (already with resource block

Platform:
```
tofu -v
OpenTofu v1.7.0-alpha1
on windows_amd64
```

Steps to reproduce are the same, but the error:

> │ Error: Unsupported argument
> │
> │   on main.tf line 32, in import:
> │   32:   for_each = { for idx, name in var.ssm_parameters_names_list : idx => name }
> │
> │ An argument named "for_each" is not expected here.
> ╵
> 
> ╷
> │ Error: Unsupported argument
> │
> │   on main.tf line 32, in import:
> │   32:   for_each = { for idx, name in var.ssm_parameters_names_list : idx => name }
> │
> │ An argument named "for_each" is not expected here.
> ╵
> 
> ╷
> │ Error: Invalid expression
> │
> │   on main.tf line 33, in import:
> │   33:   to = aws_ssm_parameter.test[each.key]
> │
> │ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls, template expressions, etc are allowed here.
> ╵
> 
> ╷
> │ Error: Invalid expression
> │
> │   on main.tf line 33, in import:
> │   33:   to = aws_ssm_parameter.test[each.key]
> │
> │ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls, template expressions, etc are allowed here.

### Did you test the state encryption?

Tested, worked

### Additional feedback / details on the state encryption

Tested on both ways, works well with local type.

### Did you test the removed block?

Tested, worked

### Additional feedback / details on the removed block

Works well

### Did you test the testing feature changes?

Tested, worked

### Additional feedback / details on the testing feature changes

works well

### Did you test the built-in functions?

Tested, worked

### Additional feedback / details on the built-in functions

Works well.

### Did you test the CLI changes?

Tested, did not work / had problems

### Additional feedback / details on the CLI changes

For Linux works well, but for windows still have problems:

```
PS D:\opentofu-course\release> tofu -v
OpenTofu v1.7.0-alpha1
on windows_amd64
PS D:\opentofu-course\release> tofu init -json
Usage: tofu [global options] init [options]
...
```

**Comment by cube2222** [comment]
Hey @ShadowScorpion, thanks a lot for submitting this (I see that you tested on beta, and have just shown what happens in alpha too), we'll investigate it.

One thing, would you be able to check if it works if you use a `for_each` in the aws_ssm_parameter.test resource?

That is, right now your resource has `count` while the import uses `for_each`, so in a sense they use different patterns. I'd be curious to know if it's working if you use `for_each` in both places.

Generally, I suspect some type issues here, like `for_each` making the index a string, while the indices created by `count` are integers.

**Comment by ollevche** [comment]
Hey @ShadowScorpion!

As @cube2222 mentioned earlier there's an issue with types inside the import block, here is the fixed snippet:

```
import {
  for_each = { for idx, name in var.ssm_parameters_names_list : idx => name }
  to = aws_ssm_parameter.test[tonumber(each.key)]
  id = each.value
}
```

However, this produces another error which we successfully fixed in the https://github.com/opentofu/opentofu/pull/1530

Thank you for submitting the issue!

**Comment by ShadowScorpion** [comment]
Thanks to all for the answers and apologies for the late response.
I upgraded the OpenTofu version to beta, and the issue with CLI and JSON format was indeed fixed, although the problem with import still exists. 

I did deeper tests with two variants, "count" and "for_each" inside of the AWS EC2 instance resource. I hope this helps.
Tested on both platforms (OpenTofu v1.7.0-beta1 on windows_amd64 and OpenTofu v1.7.0-beta1 on linux_amd64).

Steps. 
First, I created the resource on my environment:

```
variable "instance_tags" {
  type    = list(string)
  default = ["test1", "test2"]
}

# version with for_each
resource "aws_instance" "web" {
  for_each = { for idx, tag in var.instance_tags : tag => idx }

  ami           = data.aws_ami.ubuntu.id
  instance_type = "t3.micro"

  tags = {
    Name = each.key
  }
}

# version with count
#resource "aws_instance" "web" {
#  count         = length(var.instance_tags)
#
#  ami           = data.aws_ami.ubuntu.id
#  instance_type = "t3.micro"
#
#  tags = {
#    Name = var.instance_tags[count.index]
#  }
#}
```

That was completed, so that after cleaning up the state, I attempted to import them with the new variable of IDs:

```
variable "instance_ids" {
  type    = list(string)
  default = ["i-08556ff2bb21a5a45", "i-02cd9942513ade5g6"]
}

import {
  for_each = { for idx, name in var.instance_ids : idx => name }
  to = aws_instance.web[tonumber(each.key)]
  id = each.value
}
```

For both of these cases, the import has failed (but with different errors).

Error when used for_each:

> │ Error: Configuration for import target does not exist
> │
> │ The configuration for the given import aws_instance.web[0] does not exist. All target instances must have an associated configuration to be imported.
> |
> │ Error: Configuration for import target does not exist
> │
> │ The configuration for the given import aws_instance.web[1] does not exist. All target instances must have an associated configuration to be imported.



Error when used count:

> │ Error: Reference to "count" in non-counted context
> │
> │   on main.tf line 34, in resource "aws_instance" "web":
> │   34:     Name = var.instance_tags[count.index]
> │
> │ The "count" object can only be used in "module", "resource", and "data" blocks, and only when the "count" argument is set.



If I've made any mistakes in the implementation, please do let me know. 
However, I've attempted to follow the example provided in the release notes as closely as possible.

Thanks,
-K

**Comment by ShadowScorpion** [comment]
@cube2222 , @ollevche , do you have any ideas about what the problem might be?

**Comment by ollevche** [comment]
Hey @ShadowScorpion!

We released a [v1.7.0-rc1](https://github.com/opentofu/opentofu/releases/tag/v1.7.0-rc1) with the fix yesterday. Could you please check with the latest version?

**Comment by ShadowScorpion** [comment]
Unfortunately, the issue still exists...

**Comment by ShadowScorpion** [comment]
Unfortunately, the issue still exists...

**Comment by ShadowScorpion** [comment]
Great! It's working now with "count" in resource. Thanks for the support.

**Comment by ollevche** [comment]
@ShadowScorpion it also works with `for_each`. I believe there's a key mismatch in the example you provided. It uses "test1" and "test2" in resource and 0, 1 in import. Try querying resource instances by tags instead of by indices in the import statement.

Once again, thank you for the bug report!
